### ISSUE TITLE
How to use with typescript?

### ISSUE THREAD

**Issue by vctormb** [Bkucera/cypress-plugin-tab#1]
How can I use it with TS?

I see that the types are been exported, but I don't know how to add it in cypress to detect in the lint.

Thanks!

**Comment by Bkucera** [comment]
have you placed `require('cypress-plugin-tab')` in your support/index or you spec file?

**Comment by Bkucera** [comment]
I do need to update the type definitions to add a `declare`.

**Comment by vctormb** [comment]
> have you placed `require('cypress-plugin-tab')` in your support/index or you spec file? I'm able to get type completions in a .ts file either way.
> 
> ![image](https://user-images.githubusercontent.com/14625260/58271226-9234b580-7d59-11e9-897d-48097de1e9c2.png)

Yep, I've added but did not work for me.. I just copied your type and paste inside my types file to work.

**Comment by vctormb** [comment]
> I do need to update the type definitions to add a `declare`.

Btw I was testing the `Tab` + `Shift` functionality and sometimes it works properly and sometimes not. I need to open an issue for that.

**Comment by Bkucera** [comment]
@vctormb should be fixed now. 

> Btw I was testing the Tab + Shift functionality and sometimes it works properly and sometimes not. I need to open an issue for that.

please do!

**Comment by JohnLukeBentley** [comment]
I'm also struggling to get this working in Typescript. What I've done:

* Installed with `npm install -D cypress-plugin-tab`
* To tsconfig.json added "cypress-plugin-tab/src" (this successfully removes complaints about `.tab()` in my code).

      {
        "compilerOptions": {
          ...
          "types": ["cypress", "node", "cypress-plugin-tab/src"]     
        },
* To index.d.ts added `require('cypress-plugin-tab');` at the top. I also tried `require('cypress-plugin-tab/src');`
* In my e2e\main.cy.ts I have a `.tab()`

When I run my cypress test I'm getting an error: "cy.get(...).type(...).should(...).tab is not a function".

Am I missing something?

**Comment by subinpratap** [comment]
@kuceb 
I am able to run tests in a .js file on local. However in pipeline I'm getting an error: "cy.get(...).type(...).should(...).tab is not a function".

Any ideas on how to fix this or why I could be getting it?

Usage steps:
1. Installed with npm install -D cypress-plugin-tab
2. Placed require('cypress-plugin-tab') in support/index.ts

**Comment by quentinm3** [comment]
Hello, I'm still experiencing this issue with 1.0.5, why the subject was closed ?
Thanks

**Comment by subinpratap** [comment]
@quentinm3 Are you facing issues on your local machine? I think it got closed because most of us got this working on our local.
